# Generated by Django 5.2 on 2025-04-26 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_userprofile_address_userprofile_birthday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('pickup_option', models.CharField(blank=True, choices=[('self_delivery', 'Self-delivery'), ('request_pickup', 'Request pickup')], max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('donation_type', models.CharField(choices=[('donate', 'Donate'), ('waste', 'Waste')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
