# Generated by Django 5.2 on 2025-05-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_donation_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
