# Generated by Django 5.2 on 2025-05-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_donation_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='accepted',
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
